import MyContext from '@/Helper/Context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyContext>{children}</MyContext>
      </body>
    </html>
    // Yaha par context aaise rakha hay jaise bread ka packet fridge me rakha ke jisko bhi chhayea vo le sakta hay. Vaise he context ke value layout me add karenge to jis JS file ko vo context chhayea vo JS file le lega.
  )
}